import Head from "next/head";

export const CardsProduct = () => {
    return(
        <div lang="pt-br">
        <Head>
            <title>Create Next App</title>
            <meta charSet="utf-8"></meta>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container mt-5 mb-3">
            <div className="row">
                <div className="col-md-4">
                    <div className="card-product card-electro p-3 mb-2">
                        <div className="d-flex justify-content-between">
                            <div className="d-flex flex-row align-items-center zoom-product">
                                <div className="icon-product"> <i className="fas fa-laptop" style={{fontSize: '21px'}}></i> </div>
                                <div className="ms-2 c-details badge1">
                                    <span className="mb-0">Electronics</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-md-4">
                    <div className="card-product card-joias p-3 mb-2">
                        <div className="d-flex justify-content-between">
                            <div className="d-flex flex-row align-items-center zoom-product">
                                <div className="icon-product"> <i className="fas fa-gem" style={{fontSize: '21px'}}></i> </div>
                                <div className="ms-2 c-details badge2">
                                    <span className="mb-0">Jewelery</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-md-4">
                    <div className="card-product card-roupas p-3 mb-2">
                        <div className="d-flex justify-content-between">
                            <div className="d-flex flex-row align-items-center zoom-product">
                                <div className="icon-product"> <i className="fas fa-tshirt" style={{fontSize: '21px'}}></i> </div>
                                <div className="ms-2 c-details badge3">
                                    <span className="mb-0">Men's and Women's clothing</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    )
}